/*
 * Service suggestions api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ErrorError struct for ErrorError
type ErrorError struct {
	// Код ошибки
	Code int32 `json:"code"`
	// Список ошибок
	Messages []string `json:"messages"`
}
