/*
 * Service suggestions api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Error struct for Error
type Error struct {
	Error ErrorError `json:"error"`
}
