openapi: 3.0.0
info:
  title: Service suggestions api
  version: 1.0.0
servers:
- url: /
tags:
- name: general
paths:
  /legal_suggester_service/suggestions/search:
    get:
      description: Поиск юр. лиц
      operationId: legal_suggester_service_suggestions_search_get
      parameters:
      - description: Запрос, для которого нужно получить подсказки
        explode: true
        in: query
        name: query
        required: true
        schema:
          example: пао сбербанк
          type: string
        style: form
      - description: Максимальное кол-во найденных совпадений
        explode: true
        in: query
        name: count
        required: true
        schema:
          example: "5"
          type: string
        style: form
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Suggestion'
                type: array
          description: OK
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Not Found
      summary: Поиск юр. лиц
      tags:
      - default
components:
  parameters:
    QueryQuery:
      description: Запрос, для которого нужно получить подсказки
      explode: true
      in: query
      name: query
      required: true
      schema:
        example: пао сбербанк
        type: string
      style: form
    QueryCount:
      description: Максимальное кол-во найденных совпадений
      explode: true
      in: query
      name: count
      required: true
      schema:
        example: "5"
        type: string
      style: form
  responses:
    NotFound:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Not Found
    BadRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Bad Request
    Suggestion:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Suggestion'
      description: Найденные компании
  schemas:
    Error:
      properties:
        error:
          $ref: '#/components/schemas/Error_error'
      required:
      - error
      type: object
    Suggestion:
      example:
        ogrn: ogrn
        contactPhones:
        - contactPhones
        - contactPhones
        directorFullName: directorFullName
        inn: "7707083893"
        name: ПАО СБЕРБАНК
        registrationDate: registrationDate
        kpp: "775001001"
        fullWithOpf: ПУБЛИЧНОЕ АКЦИОНЕРНОЕ ОБЩЕСТВО 'СБЕРБАНК РОССИИ'
        legalAddress: г. Москва, ул Вавилова, д 19
        shortWithOpf: ПАО СБЕРБАНК
        okpo: okpo
      properties:
        inn:
          description: ИНН
          example: "7707083893"
          type: string
        kpp:
          description: КПП
          example: "775001001"
          type: string
        okpo:
          description: ОКПО
          type: string
        ogrn:
          description: ОГРН
          type: string
        name:
          description: Наименование компании одной строкой (полное) unrestrictedValue
          example: ПАО СБЕРБАНК
          type: string
        legalAddress:
          description: Адрес организации одной строкой
          example: г. Москва, ул Вавилова, д 19
          type: string
        registrationDate:
          description: Дата регистрации в формате Y-m-d
          type: string
        directorFullName:
          description: Должность руководителя
          type: string
        contactPhones:
          items:
            type: string
          type: array
        fullWithOpf:
          description: Полное наименование с ОПФ
          example: ПУБЛИЧНОЕ АКЦИОНЕРНОЕ ОБЩЕСТВО 'СБЕРБАНК РОССИИ'
          type: string
        shortWithOpf:
          description: Краткое наименование с ОПФ
          example: ПАО СБЕРБАНК
          type: string
      type: object
    Error_error:
      properties:
        code:
          description: Код ошибки
          type: integer
        messages:
          description: Список ошибок
          items:
            type: string
          type: array
      required:
      - code
      - messages
